#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Not needed?
source ${OPENSHIFT_PYTHON_DIR}/virtenv/bin/activate
cd $OPENSHIFT_REPO_DIR
echo "Executing 'python manage.py migrate'"
python manage.py migrate

echo "Executing 'python manage.py collectstatic --noinput -v0'"
python manage.py collectstatic --noinput -v0
