# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField()),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('owning_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umklapp.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('corresponding_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umklapp.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='storypart',
            name='teller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umklapp.Teller'),
        ),
        migrations.AddField(
            model_name='story',
            name='tellers',
            field=models.ManyToManyField(related_name='tellers', to='umklapp.Teller'),
        ),
        migrations.AddField(
            model_name='story',
            name='whose_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umklapp.Teller'),
        ),
    ]
