# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0002_auto_20160528_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tellers',
        ),
        migrations.AlterField(
            model_name='teller',
            name='corresponding_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tellers', to='umklapp.Story'),
        ),
    ]
