# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 19:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0003_auto_20160528_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='whose_turn',
            field=models.IntegerField(),
        ),
    ]
