# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0006_storypart_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='42 oder: Die Antwort auf alle Fragen', max_length=256),
            preserve_default=False,
        ),
    ]
