# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0008_auto_20160528_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='hasLeft',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
