# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 09:12


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0010_story_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storypart',
            name='teller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyparts', to='umklapp.Teller'),
        ),
    ]
