# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0011_auto_20160603_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='storypart',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
