# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:50


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umklapp', '0012_charfield-limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='upvotes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
