# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umklapp', '0013_upvote-stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='skipvote',
            field=models.ManyToManyField(related_name='skipvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
