# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:44


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umklapp', '0014_skipvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='always_skip',
            field=models.ManyToManyField(related_name='skippers', to=settings.AUTH_USER_MODEL),
        ),
    ]
