# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0015_always_skip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teller',
            name='hasLeft',
        ),
    ]
