# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 07:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0016_has_left_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rules',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
