# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:33


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umklapp', '0017_story_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='read_by',
            field=models.ManyToManyField(related_name='stories_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
