# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 10:24


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umklapp', '0019_story_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypart',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='favorite_storyparts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='always_skip',
            field=models.ManyToManyField(blank=True, related_name='skippers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='stories_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='rules',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='skipvote',
            field=models.ManyToManyField(blank=True, related_name='skipvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='upvotes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
