# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0020_auto_20160621_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypart',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
