# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0021_storypart_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='skipvote',
        ),
    ]
