# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umklapp', '0023_auto_20160705_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypart',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
